name = "OptimalSlicing"
uuid = "f0c34cb3-0c18-40a1-a6e4-28571ba4e629"
authors = ["Hidetaka <u687502j@ecs.osaka-u.ac.jp> and contributors"]
version = "1.0.0-DEV"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
julia = "1.10"
